name: beat_ecoprove
description: A be@t project.
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.2
  web_socket_channel: ^2.4.0

  connectivity_plus: ^6.0.3

  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  get_it: ^7.6.4

  go_router: ^11.1.4

  image_picker: ^1.0.4

  provider: ^6.0.5
  intl: ^0.19.0
  flutter_svg: ^2.0.7
  async: ^2.11.0

  flutter:
    sdk: flutter

  flutter_rating_bar: any
  flutter_localizations:
    sdk: flutter

  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: "^0.13.1"

  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

flutter_native_splash:
  android: true
  ios: true
  image: assets/icon.png
  color: "#72AA45"
  android_12:
    color: "#72AA45"

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#72AA45"
  adaptive_icon_foreground: "assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Black.ttf
          weight: 900
        - asset: fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Lato-Regular.ttf
          weight: 400
        - asset: fonts/Lato-Thin.ttf
          weight: 100
        - asset: fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic

  assets:
    - .env
    - assets/background1/background1.svg
    - assets/background1/background2.svg
    - assets/background1/background3.svg
    - assets/background2/background1.svg
    - assets/background2/background2.svg
    - assets/register_cloth_background/register_cloth.svg
    - assets/background4/background1.svg
    - assets/background4/background2.svg
    - assets/background5/background1.svg
    - assets/background6/background1.svg
    - assets/background8/background1.svg
    - assets/background8/background2.svg
    - assets/background10/background1.svg
    - assets/level_up/leaf1.svg
    - assets/level_up/leaf2.svg
    - assets/level_up/crown.svg
    - assets/applicationTitle.svg
    - assets/nowifi.svg
    - assets/points/sustainable_points_icon.svg
    - assets/points/eco_coins_points_icon.svg
    - assets/points/eco_score_points_icon.svg
    - assets/shirt.svg
    - assets/gift-sharp.svg
    - assets/notification/notification.svg
    - assets/services/dry.svg
    - assets/services/iron.svg
    - assets/services/recycle.svg
    - assets/services/repair.svg
    - assets/services/wash.svg
    - assets/services/bucket.svg
    - assets/services/trash.svg
    - assets/services/service.svg
    - assets/services/dry/air.svg
    - assets/services/dry/machine.svg
    - assets/services/iron/less110.svg
    - assets/services/iron/less150.svg
    - assets/services/iron/less200.svg
    - assets/services/wash/dry.svg
    - assets/services/wash/hand.svg
    - assets/services/wash/less30.svg
    - assets/services/wash/less50.svg
    - assets/services/wash/less70.svg
    - assets/services/wash/less95.svg
    - assets/others/decoration.svg
    - assets/others/decoration1.svg
    - assets/filter/time_asc.svg
    - assets/filter/time_desc.svg
    - assets/filter/settings.svg
    - assets/icon.png
