name: beat_ecoprove
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  # dependency injection
  get_it: ^7.6.4

  flutter_svg: ^2.0.7

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background1.svg
    - assets/background2.svg
    - assets/background3.svg
    - assets/applicationTitle.svg
