name: beat_ecoprove
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  # dependency injection
  get_it: ^7.6.4

  go_router: ^11.1.4

  image_picker: ^1.0.4

  provider: ^6.0.5
  intl: ^0.18.1
  flutter_svg: ^2.0.7

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background1/background1.svg
    - assets/background1/background2.svg
    - assets/background1/background3.svg
    - assets/background2/background1.svg
    - assets/background2/background2.svg
    - assets/applicationTitle.svg
    - assets/default_avatar.png
