name: beat_ecoprove
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.2

  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  get_it: ^7.6.4

  go_router: ^11.1.4

  image_picker: ^1.0.4

  provider: ^6.0.5
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  palette_generator: ^0.3.3+3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_rating_bar: ^4.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Black.ttf
          weight: 900
        - asset: fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Lato-Regular.ttf
          weight: 400
        - asset: fonts/Lato-Thin.ttf
          weight: 100
        - asset: fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic

  assets:
    - .env
    - assets/background1/background1.svg
    - assets/background1/background2.svg
    - assets/background1/background3.svg
    - assets/background2/background1.svg
    - assets/background2/background2.svg
    - assets/applicationTitle.svg
    - assets/default_avatar.png
    - assets/salsa.png
    - assets/sueter.png
    - assets/points/sustainable_points_icon.svg
    - assets/shirt.svg
    - assets/services/dry.svg
    - assets/services/iron.svg
    - assets/services/recycle.svg
    - assets/services/repair.svg
    - assets/services/wash.svg
    - assets/services/bucket.svg
    - assets/others/decoration.svg
    - assets/others/decoration1.svg
    - assets/filter/time_asc.svg
    - assets/filter/time_desc.svg
    - assets/filter/settings.svg
